---
title: PetShop Server Class Diagram
---

%% Mermaid is a markdown language that renders charts based on simple syntax.
%% Read the documentation for class diagrams: https://mermaid.js.org/syntax/classDiagram.html
%% Consider pasting/opening this file in the Mermaid Live editor, https://mermaid.live/,
%% To see the rendered result (GitHub.com also renders the diagram online).

%% WHEN THIS CHANGES Please update the following other resources as well:
%% - class-diagram-sample.png (presents a visual overview to the students)
%% - class-diagram-complete.png (may be used as a fallback if the diagrams don't render)
%% - class-diagram-link (DOES NOT NEED TO BE UPDATED; points to the branch which updates)

classDiagram
direction TB

namespace Server {
    class ServerMain {
        +main(String[] args) void
    }
}

namespace Server.server {
    class PetServer {
        -PetService service
        -WebSocketHandler webSocketHandler
        +run(int) PetServer
        +port() int
        +stop() void
    }
}

namespace Server.service {
    class PetService {
        <<Service>>
        -DataAccess dataAccess
        +addPet(Pet)
        +listPets()
        +getPet(int id)
        +deletePet(Integer id)
        +deleteAllPets()
    }
}

namespace Server.dataaccess {
    class DataAccess {
        <<Interface>>
        +addPet(Pet)
        +listPets()
        +getPet(int id)
        +deletePet(Integer id)
        +deleteAllPets()
    }

    class MemoryDataAccess {
        -int nextId
        -HashMap~Integer, Pet~ pets
    }

    class MySqlDataAccess {
        -readPet(ResultSet rs) Pet
        -executeUpdate(String statement, Object... params) int
        -configureDatabase() void
    }

    class DatabaseManager {
        -String databaseName$
        -String user$
        -String password$
        -String connectionUrl$
        +createDatabase() void $
        +getConnection() Connection $
    }
}

namespace Shared.Exception {
    class ErrorResponse {
        String message
    }

    class ResponseException {
        -int statusCode
        +ResponseException(int statusCode, String message)
        +toJson() String
        +fromJson(InputStream stream) ResponseExpection $
        +StatusCode() int
    }
}

DataAccess <|.. MemoryDataAccess
DataAccess <|.. MySqlDataAccess
PetService ..> DataAccess
PetServer ..> PetService
ServerMain ..> PetServer
ServerMain --> MemoryDataAccess
ServerMain --> MySqlDataAccess
MySqlDataAccess --> DatabaseManager
